development:
  adapter: postgresql
  database: lesbonamis_development
  user: test
  password: test
  pool: 5
  timeout: 5432
test:
  adapter: postgresql
  database: lesbonamis_test
  user: test
  password: test
  pool: 5
  timeout: 5432

production:
  adapter: postgresql
  database: lesbonamis_production
  user: test
  password: test
  pool: 5
  timeout: 5432
